### ISSUE TITLE
Check status of PR

### ISSUE THREAD

**Issue by cconcolato** [mp4ra/mp4ra.github.io#10]
We need to add a TravisCI script that checks when someone makes a PR to make sure that the PR cannot be merged if one of the following criteria applies:
- it's touching the JS or HTML
- it's removing something from a CSV
- there's already an entry with that value in the CSV 

The TravisCI integration is easy. The writing of the checks needs work.

**Comment by dwsinger** [comment]
Except that we have an example here where they are deliberately updating/clarifying an existing prior entry that they registered...

**Comment by cconcolato** [comment]
I hadn't noticed. At least, the fact that the merge is not possible would raise the question. We probably can merge by overriding the script result.

**Comment by dwsinger** [comment]
We handle manually for now
