### ISSUE TITLE
Register new codec AV1-related Dolby Vision - 'dav1' 

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra.github.io#101]
## 1. Name of the organization making the request: Dolby

Please send contact information for that organization, should questions arise at application time or in future, in email to mp4reg at group.apple.com.

### 3.1 The type of value requested: Codecs
identify the table on the site in which your value should appear

### 3.2 The desired value (typically a four-character code): 'dav1'
This should not conflict with any existing or pending code-point visible at the publication site

### 3.3 Short description of the code-point's meaning: "AV1-related Dolby Vision consistent with ‘av01’"
example descriptions are on the site

### 3.4 Link to the documentation/specification: existing "Dolby Vision"
link to the place where more information about the code-point can be found (ideally, identification of a published defining specification or other document). If you link to contact information for requesting documentation, please be as specific as possible.

### 3.5 Any other values needed to complete the request: none
notably, any other data needed for the row of the table into which the code-point will be placed.

**Comment by cconcolato** [comment]
Regarding 3.4, isn't there a link to point to?

**Comment by mikedo** [comment]
Yes. The link currently exists as "Dolby Vision".

**Comment by dwsinger** [comment]
PR has been merged, closing

**Comment by podborski** [comment]
@mikedo which DV spec actually deals with it? I looked in the “Dolby Vision Streams Within the ISO Base Media File Format Version 2.2” but I can not find anything about `dav1` there.
