### ISSUE TITLE
CMAF Media Profile - HEVC HDR10 w SCTE Dynamic Metadata App #1

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra.github.io#109]
## 1. Name of the organization making the request: Dolby

Please send contact information for that organization, should questions arise at application time or in future, in email to mp4reg at group.apple.com.

### 3.1 The type of value requested: brand
identify the table on the site in which your value should appear

### 3.2 The desired value (typically a four-character code) 'cdm1'
This should not conflict with any existing or pending code-point visible at the publication site

### 3.3 Short description of the code-point's meaning: CMAF Media Profile - HEVC HDR10 w SCTE Dynamic Metadata App #1
example descriptions are on the site

### 3.4 Link to the documentation/specification: www.scte.org (SCTE 215-1-1)
link to the place where more information about the code-point can be found (ideally, identification of a published defining specification or other document). If you link to contact information for requesting documentation, please be as specific as possible.

### 3.5 Any other values needed to complete the request
notably, any other data needed for the row of the table into which the code-point will be placed.

**Comment by mikedo** [comment]
See PR https://github.com/mp4ra/mp4ra.github.io/pull/122

**Comment by podborski** [comment]
I believe we addressed this issue. Please feel free to re-open if I'm wrong.

**Comment by mikedo** [comment]
Addressed
