### ISSUE TITLE
mvdr vs 3dpr

### ISSUE THREAD

**Issue by podborski** [mp4ra/mp4ra.github.io#138]
`mvdr` is regisered and described as `MVDDepthResolutionBox`. However, in Part 15 there is no `mvdr` defined and `MVDDepthResolutionBox` is defined as:

```cpp
class MVDDepthResolutionBox extends Box('3dpr') {...}
```

I guess we should change `mvdr` to `3dpr`.

**Comment by dwsinger** [comment]
something is nagging at me that the typo is the 3dpr here, but I don't remember

is 3dpr defined somewhere else?

**Comment by podborski** [comment]
`3dpr` also appears in the overview Table (Section 7.2):

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

  |   | 3dpr |   | MVD Depth Resolution Box | Provides the resolution of depth views (for MVD streams only)
-- | -- | -- | -- | -- | --
</div></html>

But I can not find `mvdr` anywhere.

**Comment by podborski** [comment]
@dwsinger I see the following entry in `unlisted.csv`:

```csv
3dpr,MVDDepthResolutionBox only present in the mvdC box in a codec-specific sample entry,NALu Video
```

**Comment by dwsinger** [comment]
Yes, we previously treated boxes that were specific to a codec and went in the sample entry as unregistered, believing (incorrectly) that the sample entry was a private sandbox for the codec. We might want to revise that policy, but we should try to do it uniformly.

Sub-boxes of the codec config box could be considered part of a private sandbox. Maybe we need to examine the theory that there can be private sandboxes.
