### ISSUE TITLE
Update description of brand entries for DTS

### ISSUE THREAD

**Issue by pmaness** [mp4ra/mp4ra.github.io#140]
The three DTS brands, dts1, dts2 and dts3 don't specifically mention that they are CMAF brands. This was always the intention. I would like to fix this with the following text update:
dts1:  Indicates a CMAF compliant MP4 track with audio codecs dtsc, dtsh or dtse
dts2:  Indicates a CMAF compliant MP4 track with audio codec dtsx
dts3:  Indicates a CMAF compliant MP4 track with audio codec dtsy

**Comment by dwsinger** [comment]
sure; can you make a pull request?
