### ISSUE TITLE
Non-functional links on Entity Group search results

### ISSUE THREAD

**Issue by bradh** [mp4ra/mp4ra.github.io#156]
**Describe the bug**
Search results for entity groups return results where the specification link is OK, but the category link is broken.

**To Reproduce**
1. Go to 'https://mp4ra.org'
2. Click on 'Search'
3. Enter `altr`
4. Click on 'Entity Groups' in the search result
5. Note the empty page

**Expected behavior**
Clicking on 'Entity Groups' should take you to the entity groups results

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 104.0

**Additional context**
It might also be nice to have https://mp4ra.org/#/entity_group be a working link.

**Comment by cconcolato** [comment]
Thanks for the report. I can indeed reproduce the problem with Chrome on Mac.
