### ISSUE TITLE
Improve specification handling

### ISSUE THREAD

**Issue by podborski** [mp4ra/mp4ra.github.io#174]
find a better way to capture specifications. use non-dated version of specs, use JSON and group specs by SDO. This info can be useful in combination with the conformance framework.

**Comment by dwsinger** [comment]
could https://www.specref.org/ help?

**Comment by podborski** [comment]
> could https://www.specref.org/ help?

I guess it would be possible to also integrate the https://www.specref.org/ and to try keeping some of the URLs up to date or something like that. So far we just translated the mp4ra spec CSV to JSON and added a few arguments to the fields as:

```json
  {
    "specification": "ISO",
    "url": "http://www.iso.ch/",
    "description": "ISO/IEC 14496-12 & 15444-12, ISO base media file format.",
    "MPEG": true
  },
```
