### ISSUE TITLE
Full Range Constrained Baseline VVC CMAF Media Profile

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra.github.io#196]
### Name

ATSC

### Address

1300 I Street NW, Suite 400E Washington, DC 20005

### URL

https://www.atsc.org/

### Kind

Brands

### Identifier (four-character code)

cafr

### Specification

https://www.atsc.org/atsc-documents/type/3-0-candidate-standards/

### Abstract

CMAF Media Profile for ATSC Full Range Constrained Baseline VVC

### Name, Title, Organization

Michael Dolan, PearlTV, ATSC Member

### Email

m1@dolan.tv

### Date of Definition

11-16-2023

### Statement of Intention

A number of ATSC members have stated that they intend to implement this profile and thus use this brand.

**Comment by mikedo** [comment]
Contact information supplied as requested.

**Comment by podborski** [comment]
Thanks @mikedo , the only question I have is if we have to wait until the spec becomes the ATSC 3.0 standard and will be listed https://www.atsc.org/atsc-documents/type/3-0-standards/ ? We currently have this specification listed in our specifications.json

```json
 {
    "specification": "ATSC 3.0",
    "url": "https://www.atsc.org/atsc-documents/type/3-0-standards/",
    "description": "ATSC 3.0 A337 Application Signaling",
    "MPEG": false
  },
```

Any ideas?

**Comment by mikedo** [comment]
The purpose of Candidate Standard is to encourage implementations and testing to prove out the initial writing.  At some point (~6 mo?) it will be re-balloted, possibly modified, as a Standard which will be posted in the link you already have. We'd prefer that the code be registered promptly to avoid any chance of collision in the interim. Once it is posted in the Standards area, we'll do a PR to change to the Standards URL.
