### ISSUE TITLE
Clarify that all boxes should be registered

### ISSUE THREAD

**Issue by cconcolato** [mp4ra/mp4ra.github.io#23]
The MP4RA should be clearer about what is expected of boxes that are contained in a registered box. 

For example, if a spec defines a box 'fooC' that can contain other boxes like 'barX' should you register only 'fooC' or also 'barX'. I think all boxes should be registered.

Some people seem to think that 'barX' does not need to be registered because it's only used inside 'fooC'. I don't think that's the right practice as then you risk having two 'barX' boxes with different content and parsers will have to carry context (am I parsing a barX box inside the fooC context or outside?).

**Comment by dwsinger** [comment]
Best practice: registered with a single definition.
Next best practice: contextual parsing (as above, depending on the container)
Next worst practice: contextual parsing based on something else (e.g. if in a track with the XXX handler type or YYYY handler type, where that is far away from the box)
Unacceptable practice: collision with no disambiguation possible.

**Comment by dwsinger** [comment]
Propose changing this on the home page
> The registered code-points include four-character codes (4CCs) used in various ways within these file formats, and ObjectTypeIndication values used in MPEG-4 systems. The four-character codes are divided into various categories, for convenience. The largest category is the box (atom) types. The only box (atom) types which are not normally registered are boxes that are within the sample entry (sample description) for, and specific to, a codec or family of codecs, or that are used in a specific coding system (e.g. boxes used in a specific hint track).

to
The registered code-points include four-character codes (4CCs) used in various ways within these file formats, and ObjectTypeIndication values used in MPEG-4 systems. The four-character codes are divided into various categories, for convenience. The largest category is the box (atom) types. 

The current best practice is to register all box (atom) types. Historically, some that were clearly contextual were not registered, notably those
*  within the sample entry (sample description) for, and specific to, a codec or family of codecs, or 
* that are used in a specific coding system (e.g. boxes used in a specific hint track).
