### ISSUE TITLE
Geospatial properties - OGC 24-038

### ISSUE THREAD

**Issue by bradh** [mp4ra/mp4ra.github.io#239]
### Name

Open Geospatial Consortium

### URL

https://www.ogc.org/

### Kind

Item Properties

### Identifier (four-character code)

mcrs, mtxf, tiep

### Abstract

These three properties will be used to provide geospatial referencing (essentially a mapping of pixel coordinates to real-world coordinates) for image items such as Earth Observation photographs.

### Name, Title, Organization

Brad Hards

### Date of Definition

2024-08-22

### Statement of Intention

This is being implemented by multiple participants for OGC Testbed 20.

**Comment by podborski** [comment]
Contact information provided through email.

**Comment by podborski** [comment]
addressed in #241
