### ISSUE TITLE
Advanced Professional Video codec sample entry type

### ISSUE THREAD

**Issue by youngkwonlim** [mp4ra/mp4ra.github.io#242]
### Name

Samsung

### Address

Samsung-ro 129, Yeongtong-gu, Suwon-si, Gyeonggi-Do, 16677, Republic of Korea

### URL

https://samsung.com

### Kind

Sample Entry Types

### Identifier (four-character code)

apv1

### Specification

https://github.com/cpncf/apv-spec/tree/main/apv_isobmff

### Abstract

APV is a mezzanine video codec for storage, exchange and editing of professional quality video. The sample entry type identifies the track containing bitstream encoded with APV codec.

### Name, Title, Organization

Youngkwon Lim

### Email

young.l@samsung.com

### Phone

+1-650-210-1001

### Address

6105 Tennyson Pkwy, Plano, TX 75024

### Date of Definition

03-01-2024

### Statement of Intention

Samsung and the partners are implementing APV codec and file format.

**Comment by youngkwonlim** [comment]
address and phone number updated.

**Comment by bradh** [comment]
Looks like the project name has been changes. Now https://github.com/openapv/openapv/blob/main/readme/apv_isobmff.md 
?

**Comment by youngkwonlim** [comment]
Yes, we have moved our specification to open repository.
