### ISSUE TITLE
Make CNAME only present in master

### ISSUE THREAD

**Issue by edrthomas** [mp4ra/mp4ra.github.io#28]
This would avoid warning from GitHub that the CNAME is alreay taken when commits are pushed.

**Comment by podborski** [comment]
@edrthomas is this warning still occurring with GitHub Actions?

**Comment by edrthomas** [comment]
If I recall, the warning message appeared when someone forked the repo and committed something. It triggered the CI pipeline which showed the warning.

The tentative solution in the title is probably not relevant anymore and I am not sure there is still an issue here ...

Maybe close this one?

**Comment by podborski** [comment]
Closing. We can re-open if the problem occurs again.
