### ISSUE TITLE
Duplicate 'colr' box definitions

### ISSUE THREAD

**Issue by palemieux** [mp4ra/mp4ra.github.io#83]
The `colr` entry at `CSV/item-properties.csv` duplicates that at `CSV/sample-entries-boxes.csv`. The defining specification for the former explicitly states that _The colour information 'colr' descriptive item property has the same syntax as the ColourInformationBox as defined in [the latter]_

**Comment by dwsinger** [comment]
Right, that box is valid as (a) a sample-entry extension and (b) an item property, which are formally separate namespaces. So it's registered into both. What is the issue?

**Comment by palemieux** [comment]
> which are formally separate namespaces.

Oh. This not clear. Where are the "Item Property" and "Sample-entry" namespaces defined?

**Comment by dwsinger** [comment]
well, item properties are included in the item property container (only). sample entry extensions are in sample entries (only). we use the same 4CC since it's the same syntax.

**Comment by palemieux** [comment]
> item property container

Do you mean as as elements of `ItemPropertyContainerBox` as specified in ISO/IEC 23008-12?

> sample entry extensions are in sample entries (only)

Do you mean as elements of extensions of `SampleEntry` as specified in ISO/IEC 14496-12?

**Comment by dwsinger** [comment]
yes

**Comment by palemieux** [comment]
Ok. I suggest adding these clarifications in the corresponding `.csv` files and/or below the relevant heading in the generated pages, e.g. http://mp4ra.org/#/item_properties

**Comment by dwsinger** [comment]
we'll look at more specific links between the tables and the defining context.
