### ISSUE TITLE
Allow multiple defining specifications

### ISSUE THREAD

**Issue by palemieux** [mp4ra/mp4ra.github.io#84]
Some boxes might be defined in one specification, and extended by other specifications.

For example, the Colour Specification box specified in ISO/IEC 15444-1 is extended by ISO/IEC 15444-2 and ISO/IEC 15444-15.

Suggest allowing multiple defining specifications.

**Comment by mikedo** [comment]
The fact that multiple specifications are making separate versions of the same 4CC item is a document architecture problem I think.  Using the RA to provide the linkage between the documents to address this seems awkward. Can the subject documents be amended/revised to consolidate the different versions?

**Comment by palemieux** [comment]
> The fact that multiple specifications are making separate versions of the same 4CC item is a document architecture problem I think.

Yes.

Perhaps _allowing multiple defining specifications_ goes too far, what about a single defining specification supplemented by any number of informative _see also_ references?

> Can the subject documents be amended/revised to consolidate the different versions?

Ideally, yes. The first step is to identify these overlaps. Some of these overlaps might be historical and difficult to fix.

**Comment by dwsinger** [comment]
We hold this and urge the JPEG group to discuss the issue. We'd rather not change the architecture of the RA to deal with something that we feel should not happen anyway.
