### ISSUE TITLE
Deprecate Dolby OTIs A5, A6, AE

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra.github.io#85]
These OTI's are not actually defined and not in use. They should be deprecated.

**Comment by cconcolato** [comment]
Following the references from the MP4RA to the ETSI documents defining AC-3 and AC-4, I could not find any mention of the Object Type Indication. It seems reasonable to deprecate them. Do you know where they were defined in the first place?

**Comment by jeanlf** [comment]
I don't know where they come, this is likely a private request from some company.
A quick search on the web shows that it has been used for a while (GPAC, FFMPEG, chromium, exoplayer), not sure we want to deprecate them...

**Comment by mikedo** [comment]
I do know the genesis, but it is not relevant.  They are entirely undocumented and should not be used.  This means that they *can* be used if you want and you think you know what they mean.  But it is important that they not be perpetuated/encouraged going forward as they have no authoritative semantics.

**Comment by dwsinger** [comment]
Two things: for a period I was required to issue OTIs for every codec 4cc registration. In the case of at least AC-4, I was actually asked by the registrant for the OTI. However, I am fine re-labeling these code points as unused/deprecated and with a history pointer saying what they were used for. (Though should we check with the odd corners of the world using MPEG-4 systems?)

**Comment by dwsinger** [comment]
so I am hoping for a PullRequest that (a) removes the OTIs from the codecs table and (b) marks these three entries as "Unused, do not use, was ETSI xxxxx" in the OTI table.

**Comment by mikedo** [comment]
Sorry, fell off my todo list...will do a PR "soon".

**Comment by mikedo** [comment]
The "deprecate" language was mimic'd from codecs: 'ec+3' for consistency.  It's not quite the above. Also, the ETSI references to the codecs are not really helpful since the OTI codes were never there.

**Comment by dwsinger** [comment]
pull request accepted, closing
