### ISSUE TITLE
DECE ceased operations 31-July-2019

### ISSUE THREAD

**Issue by mikedo** [mp4ra/mp4ra.github.io#88]
All DECE specifications are no longer available at www.uvvu.com and any contact information is no longer valid.

**Comment by palemieux** [comment]
> uvcentral.com is now hosted by MovieLabs and will be for the foreseeable future.

**Comment by mikedo** [comment]
Good news.  The specifications.csv should be updated. And, updated contact information should be submitted to the RA by email.

**Comment by palemieux** [comment]
> And, updated contact information should be submitted to the RA by email.

Can the contact information be provided on this issue?

**Comment by dwsinger** [comment]
If you like. Email is offered as the contact information is archived but not published.

**Comment by palemieux** [comment]
Got it. I just sent an email at the registrar email address.

**Comment by dwsinger** [comment]
fixed, see PR
